#!/usr/bin/env ruby
require "#{File.dirname(__FILE__)}/../lib/wlist.rb"

parse_options
data = JSON.parse(ARGF.read)
response = patch("tasks/#{OPTIONS[:id]}", data)
puts JSON.pretty_generate(response)
