#!/usr/bin/env ruby
require "#{File.dirname(__FILE__)}/../lib/wlist.rb"


parse_options

if OPTIONS[:id]
  response = get("users/#{OPTIONS[:id]}")
else
  response = get("user")
end

puts JSON.pretty_generate(response)
