#!/usr/bin/env ruby
require "#{File.dirname(__FILE__)}/../lib/wlist.rb"

parse_options
response = delete("notes/#{OPTIONS[:id]}?revision=#{OPTIONS[:revision]}")
puts JSON.pretty_generate(response) if response
