#!/usr/bin/env ruby
require "#{File.dirname(__FILE__)}/../lib/wlist.rb"

parse_options

if !STDIN.tty?
  data = JSON.parse(ARGF.read)
else
  data = {}
end

id = data['id'] || OPTIONS[:id] # fail if neither?
data['revision'] = OPTIONS[:revision] if OPTIONS[:revision]
data['content'] = OPTIONS[:content] if OPTIONS[:content]

response = patch("notes/#{id}", data)
puts JSON.pretty_generate(response)
