#!/usr/bin/env ruby
require "#{File.dirname(__FILE__)}/../lib/wlist.rb"

if ARGV.size == 0
  puts JSON.pretty_generate(get_user)
elsif ARGV.size == 1
  puts JSON.pretty_generate(get_user(ARGV[0]))
else
  puts "Usage: ".bold.red + "wlist user [id]"
end


